/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScenarioRouteImport } from './routes/scenario'
import { Route as ProspectingRouteImport } from './routes/prospecting'
import { Route as IndexRouteImport } from './routes/index'

const ScenarioRoute = ScenarioRouteImport.update({
  id: '/scenario',
  path: '/scenario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectingRoute = ProspectingRouteImport.update({
  id: '/prospecting',
  path: '/prospecting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prospecting': typeof ProspectingRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prospecting': typeof ProspectingRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prospecting': typeof ProspectingRoute
  '/scenario': typeof ScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prospecting' | '/scenario'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prospecting' | '/scenario'
  id: '__root__' | '/' | '/prospecting' | '/scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProspectingRoute: typeof ProspectingRoute
  ScenarioRoute: typeof ScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scenario': {
      id: '/scenario'
      path: '/scenario'
      fullPath: '/scenario'
      preLoaderRoute: typeof ScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospecting': {
      id: '/prospecting'
      path: '/prospecting'
      fullPath: '/prospecting'
      preLoaderRoute: typeof ProspectingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProspectingRoute: ProspectingRoute,
  ScenarioRoute: ScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
